---
- name: "show remote environment"
  shell: env

- name: Creates uda_app directory
  file:
    path: ~/uda_app
    state: directory

- name: "copy tar file"
  become: yes
  copy:
    src: artifact.tar.gz
    dest: $HOME/uda_app/artifact.tar.gz

# - name: "copy backend binaries"
#   become: yes
#   copy:
#     src: /root/project/backend/dist
#     dest: $HOME/www/html/uda_app

# - name: "copy node_modules"
#   become: yes
#   copy:
#     src: /root/project/backend/node_modules
#     dest: $HOME/www/html/uda_app

# - name: "delete anything that might already be running"
#   become: true
#   command: pm2 delete all
#   ignore_errors: true

# - name: "start server"
#   become: true
#   command: pm2 start -f ./main.js
#   args:
#     chdir: $HOME/www/html/uda_app_backend/dist
#   environment:
#     ENVIRONMENT: production
#     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
#     TYPEORM_MIGRATIONS_DIR: "./migrations"
#     TYPEORM_MIGRATIONS: "./migrations/*.js"
#     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
#     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
#     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
#     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
#     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
#     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"