version: 2.1

orbs:

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: install dependencies
          command: |
            cd frontend && npm i
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - run:
          name: build front-end
          command: |
            npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: install backend dependencies
          command: |
            cd backend && npm i
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - run:
          name: Back-end build
          command: |
            npm run build


workflows:
  run_ci:
    jobs:
      - build-frontend
      - build-backend
